version: '3.8'
services:
  backend:
    build:
      context: ./backend # backendディレクトリにDockerfileがあることを想定
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # ホストのbackendディレクトリをコンテナの/appにマウント
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:your_root_password@db:3306/todo_db # コンテナ内部のdbサービス名で接続

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: